### ISSUE TITLE
Mode junior

### ISSUE THREAD

**Issue by s-afchar** [SimpleSoftwares/Blueflap-Universe#1]
Créer une interface dédiée aux plus jeunes

---

@Bat41 : Je pense qu'en plus d'une interface il faut un lot de fonctionnalités supplémentaires. Je penses notamment à :

Whitelist/Blacklist de site définie par les parents (ou automatiquement) et modifiable avec un code
Pourquoi ne pas permettre plusiquers comptes avec différents réglages ? (Un pour l'enfant, un autre pour son père, un autre pour sa mère) Ca peut être utile sur les ordis familiaux.

---

@the-new-sky : Le sujet date un peu mais j'y ajoute mes idées :

-Bloquer le téléchargement, en cas de téléchargement le mot de passe parents est requis.

-Limitation du temps et des horaires de connexion.

-Historique ineffaçable sans mot de passe.

-Utilisation de WOT pour observer la réputation des sites Web et bloquage de ceux qui ont une mauvaise réputation.

**Comment by elegaanz** [comment]
Peut-être mettre Qwant Junior comme moteur de recherche par défaut ?

**Comment by s-afchar** [comment]
Prévu

**Comment by s-afchar** [comment]
Fonctionnalité annulée
