### ISSUE TITLE
Page nouvel onglet

### ISSUE THREAD

**Issue by ghost** [SimpleSoftwares/Blueflap-Universe#22]
Avoir une page nouvel onglet/accueil pourrait être sympa.

**Comment by ghost** [comment]
Petit WIP fait en vitesse : 

![wip bf final](https://cloud.githubusercontent.com/assets/7465699/9722077/8303ed42-559e-11e5-9ce3-e07a50496cf0.png)

Dites si ça vous plaît ^^ !

(Faites pas attention au trait rouge, c'est un repère que j'ai oublié de cacher :-° )

**Comment by s-afchar** [comment]
Flux = Flux RSS ?
J'y réfléchirai pour le nouveau Bluestart :smile:

**Comment by s-afchar** [comment]
![](http://vpictu.re/uploads/c467c3fd6565b2c6e45c69dac35a8b8c09b9cb31.JPG)

Pour l'instant Bluestart ressemble à ça mais je vais intégrer ton idée de flux RSS

**Comment by s-afchar** [comment]
Je suis en train de refaire Bluestart avec un stackpanel pour qu'il soit modulable. Comme ça on pourra ajouter des blocs flux rss etc... + Ajout des suggestions smartsuggest

Comme tu peux le voir ci-dessous, ça se rapproche un peu plus de ta maquette :smiley: 

![](http://vpictu.re/uploads/7d4aeed05cd1170078690a21e3f1d8f049f491b6.PNG)

![](http://vpictu.re/uploads/e309e5d31fc8aa6c15725bef80efcf3990950d17.PNG)
