### ISSUE TITLE
Mettre à jour le .gitignore

### ISSUE THREAD

**Issue by elegaanz** [SimpleSoftwares/Blueflap-Universe#25]
Les fichiers dans /obj et /bin sont envoyés sur Github, alors qu'ils ne devraient pas. Ca met quatre ans à cloner du coup, pour des fichiers inutiles.

**Comment by elegaanz** [comment]
En plus ça fausse le stats : Github affiche que le projet est surtout en C# et Powershell ...

**Comment by s-afchar** [comment]
J'ai mis à jour le GitIgnore mais je n'ai pas l'impression que quelque chose ai changé... Tu peux vérifier ? https://github.com/SimpleSoftwares/Blueflap-Universe/blob/master/.gitignore

**Comment by elegaanz** [comment]
Comme je t'ai dis par MP sur ZdS, il faut aussi virer les dossier du Github.

**Comment by s-afchar** [comment]
C'est fait
