### ISSUE TITLE
Image d'arrière plan multithreadée

### ISSUE THREAD

**Issue by elegaanz** [SimpleSoftwares/Blueflap-Universe#28]
Il faudrait charger l'image d'arrière plan de BlueStrart dans un autre thread si possible, parce que ça fait freezer Blueflap, voir tout le PC.

**Comment by elegaanz** [comment]
En fait je sais pas si c'est vraiment l'image d'arrière plan ... C'est peut-être toutes les manips faites au départ ...

**Comment by s-afchar** [comment]
Ça à l'air d'être plutôt le moteur Edge selon moi. Si tu regarde cet autre Browser du Windows Store https://www.microsoft.com/store/apps/9nblggh1z7vx tu vois que lui aussi il a des petits moments de Freeze

**Comment by elegaanz** [comment]
Bon, c'est un peu chiant, mais il va falloir faire avec alors ... On ferme l'issue ?

**Comment by elegaanz** [comment]
En fait je crois bien que c'est BlueStart qui fait ça. Si on le met pas en page d'accueil, il y a aucun freeze.
