### ISSUE TITLE
Gérer les permissions

### ISSUE THREAD

**Issue by elegaanz** [SimpleSoftwares/Blueflap-Universe#40]
Quand un site web demande une permission l'utilisateur n'en sait rien et elle est automatiquement refusée.

**Comment by s-afchar** [comment]
Je ne pense pas que l'on puisse récupérer ces infos avec le contrôle Webview qui est certes rapide, mais limité

**Comment by elegaanz** [comment]
Si, on peut via je ne sais plus quel event.

**Comment by s-afchar** [comment]
Ce sera ajouté dans la prochaine mise à jour 😉 

![](https://www.dropbox.com/s/k0i59m3uhwcov8i/Capture.PNG?dl=1)
