### ISSUE TITLE
Keyboard autocompletion feature is too aggressive.

### ISSUE THREAD

**Issue by JKnightGURU** [SimpleSoftwares/Blueflap-Universe#47]
Currently searching "cpp memmove" ends up with "cop me move". This is... acceptable for texting, but search field should restrict any automatic actions without explicit tap on the word on top of keyboard. I actually tried doing this 3 or 4 times, but then I gave up. Edge's search field overrides that. Probably there's already an issue of this kind, but I don't speak French.

**Comment by jknightguru** [comment]
By the way, releasing Blueflap under GPL is great! Keep up good work and expect further issues:-)

**Comment by jknightguru** [comment]
I meant autocorrection. :-/ Sorry.

**Comment by jknightguru** [comment]
Turning autocorrection globally is a workaround. But... You know.

**Comment by s-afchar** [comment]
Okay, I'll try to fix that

**Comment by s-afchar** [comment]
Fixed in the future update
