### ISSUE TITLE
Original Blueflap

### ISSUE THREAD

**Issue by JasonHK** [SimpleSoftwares/Blueflap-Universe#50]
How can I get the original Blueflap browser?

**Comment by s-afchar** [comment]
We don't support Blueflap 3.x anymore. However you can download it by clicking this link : https://www.dropbox.com/s/dvx5sulj219h8o2/Blueflap3_3_Setup.exe?dl=1

**Comment by JasonHK** [comment]
Thanks. But I thank you can keep the source on GitHub, I maybe useful for someone who wants to maintain it. ;-)
