### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by ghost** [SimpleSoftwares/Blueflap-Universe#60]
It is easier to handle tabs than windows. Maybe do the tabs along the sidebar, underneath the other icons.

Apart from a few UI inconsistencies, it's a beautiful app. I'd use it all the time, but the lack of tabs and bugs here and there are keeping me using Edge.

**Comment by s-afchar** [comment]
Indeed, impleting tabs is one of my goals (but I don't have a lot of time these days). For the moment, TaskView is OK on Windows Mobile and Windows Tablet Mode. The main issue is on PC.

What UI inconsistencies did you notice ?

**Comment by s-afchar** [comment]
Redondant avec issue #45
